version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_project_shad
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DB_NAME} || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db
    volumes: 
      - .:/app
    networks:
      - fastapi_project_shad

    entrypoint: ["/bin/sh", "/usr/local/bin/docker-entrypoint.sh"]

networks:
  fastapi_project_shad:
    name: fastapi_project_shad
