version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    restart: always
    ports:
      - "5445:5432"
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_project_shad

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_pass
      - DB_NAME=fastapi_project_db
    depends_on:
      - db
    volumes: 
      - .:/app

    networks:
      - fastapi_project_shad

networks:
  fastapi_project_shad:
    name: fastapi_project_shad
